### ISSUE TITLE
classpath 'com.android.tools.build.gradle:1.3.0'

### ISSUE THREAD

**Issue by AndroidGecko** [mgouline/android-samples#3]
after changing to
classpath 'com.android.tools.build.gradle:1.3.0'

* What went wrong:
Execution failed for task ':tasks'.
> Could not determine the dependencies of task ':app:testBlueDebugCoverage'.

**Comment by mgouline** [comment]
60b57a53cd98019e96e8522c01e9624f5396d2f3
